### PR TITLE
Bugfix realty filter mapping

### PR DESCRIPTION
**Pull request by infabo**

### CODE REVIEW

**Comment by simitter** [comment]
@19Gerhard85 du hast das umgestellt, weisst du noch warums da gegangen ist?
c4270584996cf3980222c8d4731c4ce89aeb45ed

**Comment by infabo** [comment]
witzig :grin:

**Comment by zoltan-sule** [comment]
@Tschebel , @19Gerhard85 , @infabo 

We adjust the logic on the server side and that will fix the issue of the filtering by area.

**Comment by infabo** [comment]
@zoltan-sule when will this fix be deployed?

**Comment by zoltan-sule** [comment]
@infabo the fix has been deployed

**Comment by infabo** [comment]
@zoltan-sule working now! Thank you for the fix!

**Pull request merged**
